### ISSUE TITLE
[1.1.3] Client Meeting

### ISSUE THREAD

**Issue by DeNhAiKal** [DeNhAiKal/INF2001_P5-5#21] opened 2023-09-13 10:43 UTC
<details><summary>Task Title ID</summary>
<p>
#21
</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Task Details</summary>
<p>

`Conduct a client meeting and record all the findings to be reviewed`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Goals</summary>
<p>

`Able to note down all the details that the client gave.`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Success - Completion Details:</summary>
<p>

`A successful client meeting `

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Allocated time</summary>
<p>

`1 day`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`7/09/2023` - `7/09/2023`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Person In-charge</summary>
<p>

- [ ] Den

- [ ] Hakim

- [ ] Zac

- [x] Brendan

- [ ] Rudhi

- [ ] Malcolm 
</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Task Status</summary>
<p>

`Completed`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Current Priority</summary>
<p>

`Low priority`

</p>
</details>

**Comment by bren37** [comment] 2023-09-13 12:21
<details><summary>Work Done</summary>
<p>

Good morning Mr Chee. Thank you for taking the time to meet with us today. My name is Den, and I’ll be leading the team that will be working on your project. With me today is Zachary, Hakim, Malcolm, Brendan, and Rudhi, who will be playing a crucial role in this project. The objective of today’s meeting is to understand more about the company to meet your needs and expectations. 

Let us begin with the first question:
What are the constraints and challenges from your previous methods on workload management that you would like to address with this app?
- Even up to now, I have been using Excel spreadsheet, then my manager will insert the timing.
- If I need to see the workload, I will tabulate it manually or use Excel macros to total up the hours.
- Excel can still be used in such a system, because at the end when you stored it, it is still a data, or a CSV file.
- What I want is to come together and have a workload management system, that when I plan the staff workload allocation, I am be able to see the workload of every staff, like the hours worked.
- If I feel that some staffs are overworking, I can make adjust with it like going back to the senior system, I can edit and amend the hours allocation. Moreover, dedicated to aircon practices, I got different kind of practice, for example like standard servicing, they can plan and put the service hours but for ad-hoc and for my resource, I need to know how to balance it. For standard servicing, I can allocate and preplan easily.
- For those ad-hoc such as air-con spoils, people call for servicing. I might need stand-by staff to allocate for this kind of job.
- The stand-by staff also need to be allocated for situation like some staff go for urgent leave which is the same situation for an ad-hoc job.

Next, we will proceed to questions on requirements: 
i) Does the website have to be mobile friendly, or are you strictly using it on a computer?
- At this moment, a simple web-page will do but this is a low, almost zero code system. What I expect is the software design architecture system and someone can take this and do the coding. The key is to capture the functionality and the sub function from the user requirement and the user functionality.
- Ideally when I want to upgrade 1 function, I should be able to easily extend and replace (modernization, instead of modification.)
- At the start, web-based will be fine.

ii) How do you want it visualized on the landing page? (By staff, by date/time/calendar, by workload)? What kind of information to show along with workload? (Staff name, type, timing)? How to visualize workload for each staff type? (Driver, technician)
- I want it to have a feature that allows me to choose and configure what I want to see (eg, if I want it to be calendar format, I can view it as that and if I want it to be in chart format, I should be able to change the view)
- It should be able to select it before I view anything.
- For the visual, I would need my user to test it out first and then they can feel it.
- At the start, I should be able to see which staff are allocated for the workload for the week.
- I think Requirements 2,4 and 5 are interrelated.
- My workflow should be seamless, from my planning to my visualization.
- In this context, aircon servicing got shifts, and those who worked on the weekend and their preferences. All these should be captured for functional wise.

iii) Can this be edited later on? How are jobs allocated? By hours? Per location?
- As stated, it can be planned up to 5 weeks ahead. You can do it in a way that 1 month ago should be tentatively planning, Monday is the allocated date, so it should be confirmed on that day. 1 week before the allocated date should be 80%-90% confirmed.
- This is to allow the staff have a rough sensing if there is any changes to their schedule, so that the staff can be quite assured of their workload for that particular week such as where am I traveling and what am I servicing.
- Considering that the company has 2 brands of aircon, it should be taken into consideration too. 

iv) What is the relevant information? What kind of staff? (Driver, tech) How easy? What makes allocating a job easier? Is staff availability and job allocation on the same page?
- It can be any staff to be selected to view. These kind of things you guys can propose and we can test it out because managers might want to see 3 different staff.

v) Will staff be able to see the availability of other staff? Should they be able to see? If so, can the driver see tech availability? How many days before the actual day can staff edit? (e.g. cannot edit 3 days prior)
- The staff should be able to see the availability of other staff, same role.
- The staff might want to do swapping together, so it makes it easier for them.
- If the staff missed the deadline, I will take it as the staff does not have any preferences as the job is assigned to them and they did not give feedback to make a change for it.
- Last minute changes are case by case, the staff need to inform the manager for them to do the editing of the job allocation.

vi) Will staff be able to see if others prefer a job? Should they be able to see?
- The staff should be able to see an overall view of the calendar of who works on this week and the staff does not need to see the total allocated working hours, only visible to the manager.
- For the workload, the general overall workload, the hours and how often he worked on the weekend. So it will be more fair when I plan for the weekend job allocation.
- A planning for the backup staff to be stand by for servicing. And also the driver/vehicle too.

vii) Upon rejection, will the manager be informed about it? How many days before the actual day can staff reject? Can staff reject the week itself?
- The manager should be aware that the staff rejected the job.
- We can try 1 option is that when the staff were to reject the job allocation, a warning will appear. It can take it as minusing off from his allocation hours.

viii) Is this on the same web page?
- As mentioned previously for the (iii) question.

Finally, we have some domain related questions:
i) Can you elaborate on how staff can indicate their job preference for the week?
- Location based.
- Preference by timing like weekends and non-weekends
- Take it into preference that the total number of hours they can work.
- In this situation, full-time staff are taken into consideration as they need to meet the minimum working hours required.

ii) Can you elaborate on how end-users will be able to request aircon services through the app? Will there be specific details they need to provide, and how will these requests be presented to the manager?
- It is not supposed to be an AI schedule planning. It can be a 100% manual job. In the end, there is still a situation that there is a need to adjust the schedule.
- It is not supposed to be an AI schedule planning. It can be a 100% manual job. In the end, there is still a situation that there is a need to adjust the schedule.
- It will be a timeslot that they can click on, one way to expose it to the end user, another way is get called up. Ideally, my technician should be able to help them to book the timeslot, assisting the manager job.

iii) It is mentioned that employees must inform their availability by Wednesday for the upcoming week's planning. How will the system handle late submissions or changes in availability after the deadline?
- Case by case situation.

iv) For IT administrators overseeing user management, could you provide more details on what tasks they would handle? Will they also have visibility into workload data?
- Think of what a typical IT administrator should be doing. We are looking at supporting the manager to configure the features. So think of what the IT administrator can do to help to configure the features for the manager.
- Create and delete accounts, create can be branched out to other functionality and drill down further to second-order details.
- Put it as a variable in the system, then along the way when we test it out, we know it is a variable, not a hardcoded thing.
- The IT administrators should not be able to see the workload data, if he/she needs to see it, he/she needs to login to a manager account.

v) Is there a limit to the number of MCs and offs?
- Every company works differently.

vi) Are there any backup plans for unforeseen circumstances such as last minute unavailability and vehicle breakdown?
- For the case of vehicle breakdown, I should at least see how many vehicles are available for work.

vii) How do you want each staff member to be identified during login?
**Insufficient Time to ask**

viii) How long does van servicing take?
**Insufficient Time to ask**

ix) Is each driver assigned to only a particular van?
**Insufficient Time to ask**

x) For staff that have over 40 hours of jobs allocated, will they still be available for job allocation or should they be flagged out by the system?
**Insufficient Time to ask**

xi) Will the website be intranet or internet?
**Insufficient Time to ask**

xii) Should there be a single shared admin (manager) account with the same login credentials for all managers, or would you prefer to have unique login accounts for each individual manager?
- We should use the standard practice where each manager should have an account to log in.

That concludes all our questions we have for today. We would like to thank you, Mr. Chee, for your time and valuable insights.
</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Repository Commit Status</summary>
<p>

`No Commit`

</p>
</details>
---------------------------------------------------------------------------------------------------------------------------------------------- 
<details><summary>Completion Dateline Effects</summary>
<p>

`No changes to completion status`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------
<details><summary>Changes to the task</summary>
<p>

`No changes to the task`

</p>
</details>
----------------------------------------------------------------------------------------------------------------------------------------------  
<details><summary>Start Date - End Date</summary>
<p>

`07/09/2023` - `07/09/2023`

</p>
</details>

**Closed as completed** 2023-09-16 05:06 UTC
Labels: Meeting
